org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.daemon.idletimeout=3600000
org.gradle.vfs.watch=true
org.gradle.tooling.parallel=true

org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
# Ignore volatile CI paths that can invalidate the configuration cache
org.gradle.configuration-cache.inputs.unsafe.ignore.file-system-checks=\
    .gradle/build-output-cache/**
