name: Build and Test

on:
  pull_request:
    types:
      - synchronize
      - opened
      - ready_for_review
      - reopened
  push:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: neoforged/actions/checkout@main

      - name: Setup JDK 25
        uses: neoforged/actions/setup-java@main
        with:
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        env:
          # Gradle by default prioritizes same job id and same workflow over same commit
          GRADLE_BUILD_ACTION_CACHE_KEY_JOB_INSTANCE: build
        with:
          cache-read-only: false

      - name: Setup
        run: ./gradlew :createPatchWorkspace

      - name: Test
        run: ./gradlew :check

      - name: Create build
        run: ./gradlew :createDataArchive

      - name: Upload build
        uses: actions/upload-artifact@v7
        with:
          path: build/libs/neoform-*.zip
          archive: false

      - name: Publish PR artifacts
        if: ${{ github.event_name == 'pull_request' }}
        uses: neoforged/action-pr-publishing/upload@v1
